prepare:
  input_file: data.zip
  output_dir: .
preprocess:
  data_dir: data/images/train
  output_dir: outputs/preprocessed
  blur_kernel: 7
  threshold_method: adaptive
  morph_kernel: 3
segment:
  input_dir: outputs/preprocessed
  output_file: outputs/segmentation_results.pkl
  min_area: 50
  max_area: 500
  connectivity: 4
extract:
  segmentation_file: outputs/segmentation_results.pkl
  input_dir: data/images/train
  output_file: outputs/features.pkl
  hog_orientations: 12
  hog_pixels_per_cell: 8
  hog_cells_per_block: 2
  lbp_radius: 1
  lbp_points: 8
train:
  feature_file: outputs/features.pkl
  labels_dir: data/labels/train
  output_model: outputs/ocr_model.pkl
  model_name: SVM
  random_state: 42
evaluate:
  model_file: outputs/ocr_model.pkl
  images_dir: data/images/val
  labels_dir: data/labels/val
  metrics_file: outputs/metrics.csv
  predictions_file: outputs/predictions.csv
