# conf/config.yaml
defaults:
  - prepare: defaults
  - preprocess: defaults
  - segment: defaults
  - extract: defaults
  - train: defaults
  - evaluate: defaults

base:
  root_dir: /home/warley/dev/estagio-pdi/part_2
